// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIzSumlpYeD0MZTQMiUsFUxXpqh15fSV4',
    appId: '1:724422475595:web:aeee6746855552bc6072ce',
    messagingSenderId: '724422475595',
    projectId: 'wallet-5f129',
    authDomain: 'wallet-5f129.firebaseapp.com',
    storageBucket: 'wallet-5f129.appspot.com',
    measurementId: 'G-0ZVW117GKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI7TU37Iq1DczataU7RORTg94J4fkhc-8',
    appId: '1:724422475595:android:d62056adc16b5bb16072ce',
    messagingSenderId: '724422475595',
    projectId: 'wallet-5f129',
    storageBucket: 'wallet-5f129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqZe-5iXakzMy81Z7K-0MJv3YB2yhTNSI',
    appId: '1:724422475595:ios:dc59463b9b3cc6c96072ce',
    messagingSenderId: '724422475595',
    projectId: 'wallet-5f129',
    storageBucket: 'wallet-5f129.appspot.com',
    iosClientId: '724422475595-fet5scburmc5faqdadqjtgjbmosn4f4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqZe-5iXakzMy81Z7K-0MJv3YB2yhTNSI',
    appId: '1:724422475595:ios:dc59463b9b3cc6c96072ce',
    messagingSenderId: '724422475595',
    projectId: 'wallet-5f129',
    storageBucket: 'wallet-5f129.appspot.com',
    iosClientId: '724422475595-fet5scburmc5faqdadqjtgjbmosn4f4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDashboard',
  );
}
